services:
  - docker

matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      script:
        - tox
        - RELEASE_SKIP=head PYVER=2.7 ${TRAVIS_BUILD_DIR}/release-test.sh
    - os: linux
      language: python
      python: 3.5
      script:
        - tox
        - RELEASE_SKIP=head PYVER=3 ${TRAVIS_BUILD_DIR}/release-test.sh
    - os: linux
      language: python
      python: 3.6
      script:
        - tox
        - RELEASE_SKIP=head PYVER=3 ${TRAVIS_BUILD_DIR}/release-test.sh
    - os: linux
      language: python
      python: 3.7
      script:
        - tox
        - RELEASE_SKIP=head PYVER=3 ${TRAVIS_BUILD_DIR}/release-test.sh
    - os: linux
      language: python
      python: 3.8
      script:
        - tox
        - RELEASE_SKIP=head PYVER=3 ${TRAVIS_BUILD_DIR}/release-test.sh
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7 PYENV_VERSION=2.7.15
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5 PYENV_VERSION=3.5.4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6 PYENV_VERSION=3.6.3
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 PYENV_VERSION=3.7.5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 PYENV_VERSION=3.8.0

install:
  - source $TRAVIS_BUILD_DIR/travis/os_install.sh
  - pip install tox-travis

script:
  - tox

before_cache:
  - brew cleanup
cache:
  pip: true
  directories:
    - .mypy_cache
    - $HOME/.pyenv_cache
    - $HOME/Library/Caches/Homebrew
    - $HOME/.pyenv/versions

branches:
  only:
    - master
notifications:
  email: false
